image:
  repository: docker.io/bellamy/wallos
  tag: latest@sha256:6bcb9e668b79ec2a498617783572844ec2727e2b28e8dd9a067541436f43c8ac
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8282
        protocol: tcp
        targetPort: 80

persistence:
  database:
    enabled: true
    mountPath: "/var/www/html/db"
  logos:
    enabled: true
    mountPath: "/var/www/html/images/uploads/logos"

portal:
  open:
    enabled: true
