image:
  repository: docker.io/bellamy/wallos
  tag: latest@sha256:3ded3ea15bf8885a5489ae73d71894276cc70953eac5f46e51378613c0fa337a
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8282
        protocol: tcp
        targetPort: 80

persistence:
  database:
    enabled: true
    mountPath: "/var/www/html/db"
  logos:
    enabled: true
    mountPath: "/var/www/html/images/uploads/logos"

portal:
  open:
    enabled: true
