image:
  repository: docker.io/iyuucn/iyuuplus
  pullPolicy: IfNotPresent
  tag: latest@sha256:d5df7f4838a5647d1a75efb075b8d1f7f7955106bce6f16afdb48346fa029ba5
service:
  main:
    ports:
      main:
        targetPort: 8787
        port: 10188
persistence:
  config:
    enabled: true
    mountPath: "/IYUU/db"
  torrents:
    enabled: true
    mountPath: "/torrents"
  btbackup:
    enabled: true
    mountPath: "/BT_backup"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
