image:
  repository: linuxserver/snapdrop
  tag: latest@sha256:54ef8d7543de2c699883af0c514db9064bbec05ff5f22d63342f90b953d7b138
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10215
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
