image:
  pullPolicy: IfNotPresent
  repository: splunk/splunk
  tag: 9.2.1@sha256:e4c5b5c9246715c30909d3bbf06d244b0814b84b1420ad817640c8853c19bc47

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

splunk:
  acceptLicense: true
  password: changeme
  extraArgs: []

service:
  dataingest:
    enabled: true
    ports:
      dataingest:
        enabled: true
        port: 9997
        protocol: http
        targetPort: 9997
  main:
    ports:
      main:
        port: 8000
        protocol: http
        targetPort: 8000
  hec:
    enabled: true
    ports:
      hec:
        enabled: true
        port: 8088
        protocol: http
        targetPort: 8088
  management:
    enabled: true
    ports:
      management:
        enabled: true
        port: 8089
        protocol: http
        targetPort: 8089
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - secretRef:
                name: "secret"

persistence:
  appcreds:
    enabled: true
    mountPath: /opt/splunk/etc/
  config:
    enabled: true
    mountPath: /opt/splunk/var
  data:
    enabled: true
    mountPath: /splunkdata

portal:
  open:
    enabled: true
