image:
  pullPolicy: IfNotPresent
  repository: x1unix/go-playground
  tag: latest@sha256:055d3422b497f70d1a8c2f4594e380b8213b12e14260f659a3c4986a93401e5e
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APP_CLEAN_INTERVAL: 10m
            APP_DEBUG: "false"
