image:
  pullPolicy: IfNotPresent
  repository: mikenye/tar1090
  tag: latest@sha256:fd9abe494b4c3ed7cafb7db5de731003d7072c5940aad749c68d0996ac3fa17e
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8078
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BEASTHOST: <BEASTHOST>
            LAT: xx.xxxxx
            LONG: xx.xxxxx
            MLATHOST: <MLATHOST>
