image:
  repository: ghcr.io/linuxserver/grocy
  tag: 4.2.0@sha256:37adffabfcb60175b0802c8c47c023e31b82fea238a224127c46eb0cf711dca2
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10013
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
