image:
  repository: ghcr.io/linuxserver/filezilla
  tag: 3.67.0@sha256:6aff539259eff6195c2e8a9a55b5e284c4f76d09e41654388e736e8375fc4b00
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:

service:
  main:
    ports:
      main:
        port: 10035
        protocol: http
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: false

portal:
  open:
    enabled: true
