image:
  repository: ghcr.io/linuxserver/tvheadend
  pullPolicy: IfNotPresent
  tag: latest@sha256:d7154a9d7a558e5669cc1cc74728e0c817c33ce172e019a3da094cf48c481e42
service:
  main:
    ports:
      main:
        port: 9981
        targetPort: 9981
  htsp:
    enabled: true
    ports:
      htsp:
        enabled: true
        port: 9982
        targetPort: 9982
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
          env:
            RUN_OPTS: ""
