image:
  repository: ghcr.io/linuxserver/budge
  tag: 0.0.9@sha256:97376448d990bf4fea093d47ccbc9670a1a48e9a84e0b82d89fe4d39c33f0fda
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10165
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: "production"
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
