image:
  repository: ghcr.io/linuxserver/budge
  tag: 0.0.9@sha256:7df88dc6b2b7ab6daa85f0e2fe1e921ae7adbec065155a5a247cf84e5c652b67
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10165
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: "production"
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
