image:
  repository: foxxmd/multi-scrobbler
  tag: latest@sha256:2f1260be0058844771b0432eec7576b46be40c81ad4b3a781f80feef62a3df23
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 9078
        targetPort: 9078

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  open:
    enabled: true
