image:
  repository: bitnami/memcached
  pullPolicy: IfNotPresent
  tag: 1.6.28@sha256:a22bf40fa455a5445a5cf8eeff64cec8920576241c617419896f6c330d7dcade

includeCommon: true
service:
  main:
    ports:
      main:
        port: 11211
        protocol: tcp
        targetPort: 11211
portal:
  open:
    enabled: false

configmap:
  dashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"
    data:
      memcached.json: >-
        {{ .Files.Get "dashboard.json" | indent 8 }}
