image:
  pullPolicy: IfNotPresent
  repository: registry
  tag: 2@sha256:79b29591e1601a73f03fcd413e655b72b9abfae5a23f1ad2e883d4942fbb4351
persistence:
  datastoragepath:
    enabled: true
    mountPath: /var/lib/registry
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
