image:
  repository: ghcr.io/linuxserver/librespeed
  tag: 5.3.3@sha256:9e967d1ead9fc26be13e1972ccf2708ba65e146eeb842d1a6395ed6818777bdf
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10016
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
