image:
  repository: quay.io/pussthecatorg/libremdb
  pullPolicy: IfNotPresent
  tag: latest@sha256:dc6946f6a90e45ad5297949fa8a9173a69d81020ddb9603d13564517390d5753
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3000
        port: 10593
persistence:
  config:
    enabled: true
    mountPath: /opt/app
redis:
  enabled: true
  includeCommon: true
  redisUsername: default
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NEXT_PUBLIC_URL: http://localhost:3000
            NEXT_TELEMETRY_DISABLED: 1
            AXIOS_USERAGENT: "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
            AXIOS_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
            AXIOS_LANGUAGE: "en-US,en;q=0.5"
            USE_REDIS: true
            REDIS_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: url
