image:
  repository: gaseousgames/gaseousserver
  pullPolicy: IfNotPresent
  tag: v1.7.3@sha256:9979a50d1d7365c7ecc0bf965e24e25324563fb6b58ecd7cde80d53cc37fda25

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 80
        port: 5198

gaseous:
  igdb:
    id: ""
    secret: ""

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            dbhost:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            dbuser: "{{ .Values.mariadb.mariadbUsername }}"
            dbname: "{{ .Values.mariadb.mariadbDatabase }}"
            dbpass: "{{ .Values.mariadb.password }}"
            dbport: 3306
            igdbclientid: "{{ .Values.gaseous.igdb.id }}"
            igdbclientsecret: "{{ .Values.gaseous.igdb.secret }}"

persistence:
  config:
    enabled: true
    mountPath: "/root/.gaseous-server"
  logs:
    enabled: true
    mountPath: "/root/.gaseous-server/Logs"
  data:
    enabled: true
    mountPath: "/root/.gaseous-server/Data"

mariadb:
  enabled: true
  includeCommon: true
  mariadbUsername: gaseous
  mariadbDatabase: gaseous

portal:
  open:
    enabled: true
